### ISSUE TITLE
ImportError: No module named paho.mqtt.client

### ISSUE THREAD

**Issue by ComputerSmiths** [vinceskahan/weatherflow-udp-listener#1]
If I install paho-mqtt via pip, my Raspberry Pi (Debian 9.6, all up to date) grabs the piwheels.org version, which throws the error above.

If I install it from source as per https://pypi.org/project/paho-mqtt/ then it works fine.

Not _your_ problem, but you might want to mention it in your install documents...

And thanks so much for making this, I was gradually stumbling my way towards building something like the listener when I found yours.  Love it!

**Comment by vinceskahan** [comment]
Thanks for the report.

I'm not going to even attempt to track third-party packaged python modules that might/might-not match the reference copies a more typical pip install would put into place, and 'definitely' am trying to avoid worrying about os+version differences among all the os variants.

Some salt-to-taste might be needed if your particular paho-mqtt implementation doesn't work like the reference copy from pypi.org, or if it puts things into strange places (example - a 'brew install' on a Mac versus a native installation of a module on a Mac).

My 'guess' is that your installation put it somewhere not in your PYTHONPATH, but that's just a guess.
