### ISSUE TITLE
MQTT Authentication

### ISSUE THREAD

**Issue by rexfue** [vinceskahan/weatherflow-udp-listener#3]
Thank You for this super program.
Is it possible to add MQTT authentication?

**Comment by vinceskahan** [comment]
Try the updated version on the mqttlogin branch and let me know if it works for you.

**Comment by rexfue** [comment]
Thanks, but didn't work. Changes 2 lines, and it worked.
560d559
<
563c562
<                 AUTH = "{'username':\"args_username\", 'password':\"args_mqtt_password\"}"
---
>                 AUTH = dict(username = args.mqtt_user, password = args.mqtt_pass)
565c564
<                 AUTH = "{'username':\"args_username\"}"
---
>                 AUTH = dict(username = args.mqtt_user)
568d566
<

Thanks again, super program.

**Comment by vinceskahan** [comment]
sigh - yeah I really hosed up keeping the args.whatever in sync with the AUTH lines above :-)
Thanks a bunch.  Updated the branch.  Closing this issue.

Thanks for the idea !
