### ISSUE TITLE
Everything seems great.. except lightning strike data

### ISSUE THREAD

**Issue by kchristensen** [vinceskahan/weatherflow-udp-listener#4]
This could be something on my end, but I've had this up and running since my Tempest arrived last week and it's been great so far so thank you for the hard work.

This AM we had our first thunderstorm since I set things up, and while the Tempest iOS app shows many strikes (like 70), for some reason in InfluxDB I'm only seeing one datapoint in the `wf/evt/strike` measurement and no gaps in any of the other measurements that would indicate I was dropping metrics on the floor during the time of the storm.

Has anyone using this experienced something similar? I read through the code and I didn't see anything obvious, but I figured perhaps I was misunderstanding what the API is exposing during strike events.

For context, here's what the storm looks like in the Tempest app:

![Image from iOS](https://user-images.githubusercontent.com/838358/82733408-8ddf0780-9ce1-11ea-8736-5c1a9c76afa8.png)

In InfluxDB all I'm seeing is:

```
> SELECT timestamp,distance,energy FROM "wf/evt/strike" WHERE distance > 0;
name: wf/evt/strike
time                timestamp  distance energy
----                ---------  -------- ------
1590233755000000000 1590233755 1        33566947
```

Thanks in advance!

**Comment by vinceskahan** [comment]
I do direct writes to influxdb so if it's in the observation then the data should get in there unless I hosed something up in decoding the info.   I see 'some' strikes in my influxdb but not many, and not as many as the Tempest app shows me.   Perhaps it might be wise to do a REST query of your historical data and compare it with the influxdb strikes that should of course match.

My understanding of strikes is that it's like any other info, it reports what it found in that time period between the hub emitting an observation.  I did see that as the battery in the Tempest drops in voltage that they start shedding sensors and slowing down how frequently they emit values, but that doesn't explain any mismatch between WF server data and what you grabbed off the UDP broadcasts.  They should always match.

**Comment by kchristensen** [comment]
That's an interesting observation about the battery drop, I don't see a corresponding drop in voltage so I'll have to dig in to the historical data a bit to see if I can't figure out where the difference lies. I did also switch to running with `-s` so in the future if there's any unexpected data coming down the pipe it might clue me in because I'm not logging anything to stdout so it's kind of a black box.

**Comment by vinceskahan** [comment]
Oh, it was published in the forums the other day.

**Comment by vinceskahan** [comment]
my db queries for evt_strike and obs_st look like they show the same date for the last one seen here (april-22) but my WF app shows some recently, so I'm seeing the same thing. Dunno.

**Comment by vinceskahan** [comment]
Closing as not-a-bug.

Weatherflow UDP is what your station saw.  The Weatherflow REST, Websockets,  mobile app, and web displays of lightning data show far more than just what your sensor reported.  They essentially manufacture what they report for lightning based on undisclosed sources of information which includes what your sensor contributed to their data.  For details, see the WF Forums.
